### ISSUE TITLE
some issues...

### ISSUE THREAD

**Issue by p1way** [oussema/EDF-hackathon#1]
Hi Oussema (I'm PY ;))
I could compile the frontend on my personal laptop ! :+1: 
But, when I try to use the features, I encountered several issues:
- Apparently, I can reinit the contract and set its state to "Funding" within the _admin_ portal (Metamask says me that txs are _created_, _submitted_ and _confirmed_), but when I check the contract activity on the [Volta explorer](https://volta-explorer.energyweb.org/address/0x72eb9f4C517378a3dCF5a8507d2694e074e0170E), I cannot retrieve the txs (and if I do a search on the tx IDs, the engine cannot find them). What happened ? Where are these txs ?
- When I try to make a payment within the _payment_ portal, I get an error `TypeError: location.state is undefined`...[this React issue](https://github.com/ReactTraining/react-router/issues/6813) suggests that it is maybe because I use Firefox, but I doubt. What is your feeling?

Here are my two tx ID: 
1. init:  0x69ebce7d9e9c2f3cd9f3005f4a1f2319a1322b02d0b77056da2cdb92f45edc2c
2. letFunding: 0xffc7faabb39d63312d5ada92e0e9c3675cf861745369c4784623ccb85ba6db6e
These txs are on Volta, from 0xbA28268c31545B07B182F265dC9A5B1fED5a750D to 0x72eb9f4C517378a3dCF5a8507d2694e074e0170E

**Comment by oussema** [comment]
Hello PY, 

Thank you for your feedbacks, Actually there is a problem with the first explorer of Volta, but if you see the second explorer here [Volta explorer any blocks](https://explorer.anyblock.tools/ethereum/ewf/volta/address/0xba28268c31545b07b182f265dc9a5b1fed5a750d/) you will find transactions that you executed today.
